### ISSUE TITLE
Create team/id dicts in App.js and pass down to components

### ISSUE THREAD

**Issue by willda07** [opustm/frontend#62]
We'll probably need this data in every single component anyway. Makes much more sense to do it once and pass the data down than to make an API request in each component. Should cut down on a lot of repeated code.

**Comment by jvansant** [comment]
@willda07 This can be fixed in the backend: #63
Thataway the endpoint automatically builds the dictionary with id as key.

**Comment by willda07** [comment]
Ok. In some spots we'll need the dictionary the other way around too, but since it's working right now this can also be a refactor to revisit later if needed.

**Comment by jvansant** [comment]
Ok. Once I get the refactor in the backend done we can reassess this issue.
