### ISSUE TITLE
Announcement complete/acknowledgement

### ISSUE THREAD

**Issue by jvansant** [opustm/frontend#73]
Acknowledgement field is now in announcement model in DB. Let's figure out a way to do something useful with it.

Idea: create a checkbox column for users to mark when they have seen/completed the announcement(will then disappear-query needed when the announcement table loaded. but completed tasks can be queried too).

**Comment by willda07** [comment]
The tricky part with this one is that this is unique to each user for each announcement -- when one user sees the announcement but another hasn't, what does this "acknowledged" get set to?

**Comment by jvansant** [comment]
We’d have to check whether or not the logged in user Id matches any of the
acknowledgment IDs. If they match, we could decide to not load that
announcement.... we should keep thinking about this one.

**Comment by jvansant** [comment]
> The tricky part with this one is that this is unique to each user for each announcement -- when one user sees the announcement but another hasn't, what does this "acknowledged" get set to?

The DB has a ManyToMany relation with user class- so when one user has acknowledged their id will be added to the acknowledged m2m field of the announcement.

**Comment by willda07** [comment]
Just saw that. Thanks
