### ISSUE TITLE
React Testing

### ISSUE THREAD

**Issue by jvansant** [opustm/frontend#90]
## Testing React components with react-testing-library
- [ ] Announcement Creator Modal
- [ ] Event Creator Modal
- [ ] Bulletin List
- [ ] Event List
- [ ] Navigation Component
- [ ] Widget Component

**Comment by willda07** [comment]
What does "bulletin list" refer to?

**Comment by jvansant** [comment]
I think I must have said bulletin referring to renaming the announcents
page.
